---
- name: First Play
  hosts: router
  gather_facts: False
  connection: local
  tasks:
  - name: First Task
    ios_command:
      command: show version
      register: version
  - name: Second Task
    debug:
      var: version